/**
 * @file Asset model
 * @author Sam DeCoursey <samdecoursey@ksu.edu>
 * @exports AssetSchema the schema for the Asset model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Asset:
 *       type: object
 *       required:
 *         - ChainID
 *         - ContractAddress
 *         - Name
 *         - Symbol
 *       properties:
 *         AssetID:
 *           type: integer
 *           description: autogenerated id
 *         ChainID:
 *           type: string
 *           description: name of the chain
 *         ContractAddress:
 *           type: string
 *           description: asset contract address
 *         Name:
 *           type: string
 *           description: name of the asset
 *         Symbol:
 *           type: string
 *           description: symbol of the asset
 *       example:
 *           AssetID: 1
 *           ChainID: hyperliquid
 *           ContractAddress: "0x0d01dc56dcaaca66ad901c959b4011ec"
 *           Name: Hyperliquid
 *           Symbol: HYPE
 */
const AssetSchema = {
  AssetID: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  ChainID: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  ContractAddress: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  Name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  Symbol: {
    type: Sequelize.STRING,
    allowNull: false,
  },
};

export default AssetSchema;
