/**
 * @file Holding model
 * @author Sam DeCoursey <samdecoursey@ksu.edu>
 * @exports HoldingSchema the schema for the Holding model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Holding:
 *       type: object
 *       required:
 *         - UserID
 *         - AssetID
 *         - Amount
 *       properties:
 *         HoldingID:
 *           type: integer
 *           description: autogenerated id
 *         UserID:
 *           type: integer
 *           description: owner of the holding
 *         AssetID:
 *           type: integer
 *           description: asset of the holding
 *         Amount:
 *           type: decimal
 *           description: amount held
 *       example:
 *           HoldingID: 1
 *           UserID: 1
 *           AssetID: 1
 *           Amount: 2000
 *           AveragePrice: 15
 */
const HoldingSchema = {
  HoldingID: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  UserID: {
    type: Sequelize.INTEGER,
    allowNull: false,
    foreignKey: true,
    references: {
      model: "Users",
      key: "UserID",
    },
  },
  AssetID: {
    type: Sequelize.INTEGER,
    allowNull: false,
    foreignKey: true,
    references: {
      model: "Assets",
      key: "AssetID",
    },
  },
  Amount: {
    type: Sequelize.DECIMAL,
    allowNull: false,
  },
};

export default HoldingSchema;
