/**
 * @file User schema
 * @author Sam DeCoursey <samdecoursey@ksu.edu>
 * @exports UserSchema the schema for the User model
 *
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - UserAddress
 *       properties:
 *         UserID:
 *           type: integer
 *           description: autogenerated id
 *         UserAddress:
 *           type: string
 *           description: ethereum address for the user
 *       example:
 *           id: 1
 *           username: "0x0d01dc56dcaaca66ad901c959b4011ec"
 */

// Import libraries
import Sequelize from "sequelize";

const UserSchema = {
  UserID: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  UserAddress: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
  },
};

export default UserSchema;
